CREATE TABLE living_space (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    address TEXT NOT NULL,
    city TEXT NOT NULL,
    state TEXT NOT NULL,
    zip_code INTEGER NOT NULL,
    space_type TEXT NOT NULL,
    room_amount INTEGER NOT NULL,
    bathroom_amount INTEGER NOT NULL,
    pets BOOLEAN DEFAULT FALSE NOT NULL,
    price TEXT NOT NULL,
    lat TEXT NOT NULL,
    lng TEXT NOT NULL,
    includes TEXT NOT NULL,
    special_comments TEXT NOT NULL,
    date_created TIMESTAMP DEFAULT NOW() NOT NULL,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL
);