CREATE TABLE jobs (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    company TEXT NOT NULL,
    job_title TEXT NOT NULL,
    location TEXT NOT NULL,
    job_description TEXT NOT NULL,
    employment_type TEXT NOT NULL,
    compensation TEXT NOT NULL
);